syntax = "proto3";

option csharp_namespace = "Hospital.Grpc.Contracts";


service GenerationService {
  rpc Generate(stream GenerationRequest)
      returns (stream GenerationResponse);
}


message GenerationRequest {

  oneof payload {
    StartGeneration start = 1;
    BatchAck ack = 2;
  }
}


message StartGeneration {
  int32 total_count = 1; // Общее количество Appointment
  int32 batch_size = 2;  // Размер батча
}


message BatchAck {
  int32 batch_number = 1;
}


message GenerationResponse {

  oneof payload {
    // Батч данных
    AppointmentBatch batch = 1;

    // Генерация завершена
    GenerationCompleted completed = 2;

    // Ошибка генерации
    GenerationError error = 3;
  }
}


message AppointmentBatch {
  int32 batch_number = 1;
  repeated DoctorGrpc doctors = 2;
  repeated PatientGrpc patients = 3;
  repeated AppointmentGrpc appointments = 4;
}


message GenerationCompleted {
  int32 total_batches = 1;
}


message GenerationError {
  string message = 1;
}


message DoctorGrpc {
  string id = 1;
  string passport_number = 2;
  string name = 3;
  string surname = 4;
  string patronymic = 5;
  string birth_date = 6; // ISO-8601
  string specialization_id = 7;
  int32 experience = 8;
}

// --- Patient ---
message PatientGrpc {
  string id = 1;
  string passport_number = 2;
  string name = 3;
  string surname = 4;
  string patronymic = 5;
  string birth_date = 6; // ISO-8601
  string address = 7;
  GenderGrpc gender = 8;
  BloodTypeGrpc blood_type = 9;
  RhesusFactorGrpc rhesus_factor = 10;
  string phone_number = 11;
}

// --- Appointment ---
message AppointmentGrpc {
  string id = 1;
  string appointment_time = 2; // ISO-8601
  string office_number = 3;
  bool is_repeated = 4;
  string patient_id = 5;
  string doctor_id = 6;
}


enum GenderGrpc {
  MALE = 0;
  FEMALE = 1;
}

enum BloodTypeGrpc {
  BLOOD_TYPE_UNSPECIFIED = 0;
  A = 1;
  B = 2;
  AB = 3;
  O = 4;
}

enum RhesusFactorGrpc {
  RHESUS_UNSPECIFIED = 0;
  POSITIVE = 1;
  NEGATIVE = 2;
}
