// <auto-generated />
using System;
using Hospital.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Core.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRepeated")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            AppointmentTime = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            IsRepeated = false,
                            OfficeNumber = "101",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            AppointmentTime = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            IsRepeated = true,
                            OfficeNumber = "102",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            AppointmentTime = new DateTime(2025, 5, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            IsRepeated = false,
                            OfficeNumber = "103",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            AppointmentTime = new DateTime(2025, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            IsRepeated = false,
                            OfficeNumber = "104",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            AppointmentTime = new DateTime(2025, 9, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000005"),
                            IsRepeated = true,
                            OfficeNumber = "105",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            AppointmentTime = new DateTime(2025, 11, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000006"),
                            IsRepeated = false,
                            OfficeNumber = "106",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            AppointmentTime = new DateTime(2025, 2, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000007"),
                            IsRepeated = true,
                            OfficeNumber = "107",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            AppointmentTime = new DateTime(2025, 4, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000008"),
                            IsRepeated = false,
                            OfficeNumber = "108",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            AppointmentTime = new DateTime(2025, 6, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000009"),
                            IsRepeated = true,
                            OfficeNumber = "109",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            AppointmentTime = new DateTime(2025, 8, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000000"),
                            IsRepeated = false,
                            OfficeNumber = "110",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            AppointmentTime = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            IsRepeated = false,
                            OfficeNumber = "101",
                            PatientId = new Guid("c0000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Hospital.Core.Domain.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            BirthDate = new DateOnly(1975, 5, 15),
                            Experience = 20,
                            Name = "Иван",
                            PassportNumber = "1111 100001",
                            Patronymic = "Иванович",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            BirthDate = new DateOnly(1980, 3, 21),
                            Experience = 15,
                            Name = "Петр",
                            PassportNumber = "2222 200002",
                            Patronymic = "Петрович",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            BirthDate = new DateOnly(1988, 7, 9),
                            Experience = 10,
                            Name = "Анна",
                            PassportNumber = "3333 300003",
                            Patronymic = "Сергеевна",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Surname = "Смирнова"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            BirthDate = new DateOnly(1970, 11, 3),
                            Experience = 25,
                            Name = "Сергей",
                            PassportNumber = "4444 400004",
                            Patronymic = "Андреевич",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Surname = "Сидоров"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            BirthDate = new DateOnly(1983, 6, 30),
                            Experience = 12,
                            Name = "Дмитрий",
                            PassportNumber = "6666 600006",
                            Patronymic = "Михайлович",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Surname = "Орлов"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000006"),
                            BirthDate = new DateOnly(1990, 1, 17),
                            Experience = 7,
                            Name = "Михаил",
                            PassportNumber = "6412 100503",
                            Patronymic = "Романович",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Surname = "Косенко"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000007"),
                            BirthDate = new DateOnly(1985, 4, 12),
                            Experience = 9,
                            Name = "Ольга",
                            PassportNumber = "7777 700007",
                            Patronymic = "Александровна",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Surname = "Морозова"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000008"),
                            BirthDate = new DateOnly(1978, 9, 23),
                            Experience = 18,
                            Name = "Алексей",
                            PassportNumber = "8888 800008",
                            Patronymic = "Игоревич",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Surname = "Федоров"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000009"),
                            BirthDate = new DateOnly(1992, 2, 2),
                            Experience = 5,
                            Name = "Елена",
                            PassportNumber = "9999 900009",
                            Patronymic = "Степановна",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Surname = "Соболева"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000000"),
                            BirthDate = new DateOnly(1969, 12, 25),
                            Experience = 30,
                            Name = "Вячеслав",
                            PassportNumber = "0000 100010",
                            Patronymic = "Вячеславович",
                            SpecializationId = new Guid("b0000000-0000-0000-0000-000000000000"),
                            Surname = "Ряхов"
                        });
                });

            modelBuilder.Entity("Hospital.Core.Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RhesusFactor")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Address = "Ленина 1",
                            BirthDate = new DateOnly(1995, 8, 10),
                            BloodType = 0,
                            Gender = 0,
                            Name = "Андрей",
                            PassportNumber = "2222 000001",
                            Patronymic = "Иванович",
                            PhoneNumber = "+79001111111",
                            RhesusFactor = 1,
                            Surname = "Козлов"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Address = "Мира 7",
                            BirthDate = new DateOnly(1987, 4, 14),
                            BloodType = 1,
                            Gender = 1,
                            Name = "Светлана",
                            PassportNumber = "2222 000002",
                            Patronymic = "Сергеевна",
                            PhoneNumber = "+79002222222",
                            RhesusFactor = 0,
                            Surname = "Павлова"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Address = "Гагарина 10",
                            BirthDate = new DateOnly(2000, 12, 1),
                            BloodType = 2,
                            Gender = 0,
                            Name = "Никита",
                            PassportNumber = "2222 000003",
                            Patronymic = "Павлович",
                            PhoneNumber = "+79003333333",
                            RhesusFactor = 1,
                            Surname = "Сергеев"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Address = "Советская 15",
                            BirthDate = new DateOnly(1999, 3, 3),
                            BloodType = 3,
                            Gender = 1,
                            Name = "Марина",
                            PassportNumber = "2222 000004",
                            Patronymic = "Олеговна",
                            PhoneNumber = "+79004444444",
                            RhesusFactor = 1,
                            Surname = "Соколова"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Address = "Парковая 18",
                            BirthDate = new DateOnly(1985, 10, 20),
                            BloodType = 0,
                            Gender = 0,
                            Name = "Павел",
                            PassportNumber = "2222 000005",
                            Patronymic = "Андреевич",
                            PhoneNumber = "+79005555555",
                            RhesusFactor = 0,
                            Surname = "Михайлов"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Address = "Центральная 9",
                            BirthDate = new DateOnly(1993, 5, 15),
                            BloodType = 2,
                            Gender = 1,
                            Name = "Екатерина",
                            PassportNumber = "2222 000006",
                            Patronymic = "Михайловна",
                            PhoneNumber = "+79006666666",
                            RhesusFactor = 1,
                            Surname = "Новикова"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Address = "Школьная 22",
                            BirthDate = new DateOnly(1990, 11, 8),
                            BloodType = 1,
                            Gender = 0,
                            Name = "Игорь",
                            PassportNumber = "2222 000007",
                            Patronymic = "Дмитриевич",
                            PhoneNumber = "+79007777777",
                            RhesusFactor = 1,
                            Surname = "Васильев"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Address = "Молодежная 3",
                            BirthDate = new DateOnly(1998, 1, 30),
                            BloodType = 0,
                            Gender = 1,
                            Name = "Алина",
                            PassportNumber = "2222 000008",
                            Patronymic = "Станиславовна",
                            PhoneNumber = "+79008888888",
                            RhesusFactor = 0,
                            Surname = "Григорьева"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Address = "Заречная 12",
                            BirthDate = new DateOnly(1982, 7, 19),
                            BloodType = 3,
                            Gender = 0,
                            Name = "Руслан",
                            PassportNumber = "2222 000009",
                            Patronymic = "Владимирович",
                            PhoneNumber = "+79009999999",
                            RhesusFactor = 0,
                            Surname = "Александров"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000000"),
                            Address = "Пушкина 5",
                            BirthDate = new DateOnly(1992, 9, 25),
                            BloodType = 2,
                            Gender = 1,
                            Name = "Юлия",
                            PassportNumber = "2222 000010",
                            Patronymic = "Егоровна",
                            PhoneNumber = "+79000000000",
                            RhesusFactor = 1,
                            Surname = "Тарасова"
                        });
                });

            modelBuilder.Entity("Hospital.Core.Domain.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Name = "Офтальмолог"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Name = "Педиатр"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Name = "Проктолог"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Name = "Дерматолог"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Name = "Ортопед"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Name = "Эндокринолог"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000000"),
                            Name = "Психиатр"
                        });
                });

            modelBuilder.Entity("Hospital.Core.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Hospital.Core.Domain.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Core.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Core.Domain.Models.Doctor", b =>
                {
                    b.HasOne("Hospital.Core.Domain.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });
#pragma warning restore 612, 618
        }
    }
}
